Use HTTPS API
Avoid the following error:

ERROR:  While executing gem ... (RuntimeError)
    redirection forbidden: http://rubygems.org/api/v1/gems/specinfra.yaml -> https://rubygems.org/api/v1/gems/specinfra.yaml
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/open-uri.rb:226:in `open_loop'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/open-uri.rb:152:in `open_uri'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/open-uri.rb:718:in `open'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/open-uri.rb:36:in `open'
        /Users/sorah/.rbenv/plugins/gem-src/lib/rubygems_plugin.rb:51:in `api'
        /Users/sorah/.rbenv/plugins/gem-src/lib/rubygems_plugin.rb:96:in `api_uri_for'
        /Users/sorah/.rbenv/plugins/gem-src/lib/rubygems_plugin.rb:57:in `source_code_uri'
        /Users/sorah/.rbenv/plugins/gem-src/lib/rubygems_plugin.rb:89:in `git_clone_homepage_or_source_code_uri_or_homepage_uri_or_github_organization_uri'
        /Users/sorah/.rbenv/plugins/gem-src/lib/rubygems_plugin.rb:105:in `block in <top (required)>'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/installer.rb:339:in `block in run_post_install_hooks'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/installer.rb:338:in `each'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/installer.rb:338:in `run_post_install_hooks'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/installer.rb:303:in `install'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/request_set.rb:166:in `block in install'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/request_set.rb:150:in `each'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/request_set.rb:150:in `install'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/commands/install_command.rb:249:in `install_gem'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/commands/install_command.rb:295:in `each'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/commands/install_command.rb:295:in `install_gems'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/commands/install_command.rb:202:in `execute'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/command.rb:307:in `invoke_with_build_args'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/command_manager.rb:168:in `process_args'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/command_manager.rb:138:in `run'
        /Users/sorah/.rbenv/versions/trunk/lib/ruby/2.3.0/rubygems/gem_runner.rb:54:in `run'
        /Users/sorah/.rbenv/versions/trunk/bin/gem:21:in `<main>'